version: 2
updates:
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    pull-request-branch-name:
      separator: "/"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
    reviewers:
      - "nicolasbisurgi"
      - "MariusWirtz"
      # Add more individual reviewers:
      # - "username2"
      # - "username3"
      # Or assign to teams (use org/team-name format):
      # - "myorg/backend-team"
      # - "myorg/devops"
    open-pull-requests-limit: 5

  # Enable version updates for Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    pull-request-branch-name:
      separator: "/"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "python"
    reviewers:
      - "nicolasbisurgi"
      - "MariusWirtz"
      # Add more individual reviewers:
      # - "username2"
      # - "username3"
      # Or assign to teams (use org/team-name format):
      # - "myorg/backend-team"
      # - "myorg/devops"
    open-pull-requests-limit: 5