name: Build Executable

on:
  push:
    branches:
      - master

jobs:
  build-windows:
    name: Build on Windows
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build executable
        run: |
          pyinstaller --onefile `
          --name "optimuspy" `
          --add-data "execution_mode.py;." `
          --add-data "executors.py;." `
          --add-data "results.py;." `
          --hidden-import "seaborn" `
          --console optimuspy.py

      - name: Upload executable artifact
        uses: actions/upload-artifact@v4
        with:
          name: optimuspy-winOS
          path: dist/optimuspy.exe
          retention-days: 180